# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9b06a889fb0574039c0b0392206c2b56600037c09129a60562f7f17aaa95dc73558b14e57022970f2f4bb07f530835900580c2ecefb142cbded73651a1df97

test:
  secret_key_base: b612130244833165495d1b647f2a7dce06a0ef0cd77fd51d0d6366bd904a398c5f1aa917a7d8b4bcf9d1780e02ac51871180ac6cd75dafb87f71ba4331eaf6e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
